spring:
  application:
    name: portfolio-blog-system
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio_blog_db
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: "9a4f2c8d3b7e1f6c5a8b9d0e1f2c3b4a5f6e7d8c9b0a1f2e3d4c5b6a7f8e9d0c"